RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN wget -c https://mega.nz/file/gzYzxSAJ#B_nUOvqyS2rhgFUf1Rio3mSgCKLoEzwVY2qisySjQzU -O game-of-memory.tar
